### ISSUE TITLE
x/y position units not specified in README

### ISSUE THREAD

**Issue by lexelby** [inkstitch/pyembroidery#29]
The readme makes no mention of what units `x`, `y`, `dx` and `dy` are specified in.  From reading the code, I _think_ it's tenths of a millimeter like libembroidery, but I'm not 100% certain.

**Comment by tatarize** [comment]
Yeah, literally all the five formats there has it 1/10 mm. Admittedly in PCS format it may actually be scaled by 5/3rds, and some other things like .plt within HPGL for generic XY plotters use 0.025mm . But, embroidery wise, The embroidery formats uses 1/10th pretty universally units at the core. I'll make it more overt in the documentation.
