### ISSUE TITLE
CND Format - Non Issue

### ISSUE THREAD

**Issue by wwderw** [inkstitch/pyembroidery#41]
CND format is actually an outline format for specific branded software.  No embroidery info that a machine can read.  It would be like trying to use THR directly in a machine.

I'm not sure about the others in that same listing, but I'm aware of that for CND.

**Comment by tatarize** [comment]
https://github.com/inkstitch/pyembroidery/wiki/Formats

CND basically got classified in the rumor section. Libembroidery has a stub and no files appear to exist that I can generate or have access to.

**Comment by tatarize** [comment]
I'm apparently down to and Stx, Tap, Zsk for readers with both libembroidery guidance and which I can make files for, and seemingly hinky in some way that seems complex.

**Comment by wwderw** [comment]
CND files are not a rumor.  They do exist.  They just aren't embroidery files akin to a DST.

![cnd](https://user-images.githubusercontent.com/24878362/42449714-50246a9e-8347-11e8-94d1-e4fed0c86f17.png)
