### ISSUE TITLE
add version tags and update setup.py

### ISSUE THREAD

**Issue by lexelby** [inkstitch/pyembroidery#44]
The latest version on PyPI is 1.2.9, but `setup.py` still has `1.2.0`.  I find it useful to be able to check out the code matching the exact version I've pinned in `requirements.txt` in case I need to look into a bug or understand behavior that I'm seeing.

Using git tags makes this super easy because I can just do `git checkout v1.2.9` to see the source code at that version.  Perhaps you're already using tags, in which case you might need to `git push --tags`.

**Comment by tatarize** [comment]
Yeah, my update procedures are a bit weak. I update the setup.py from a different directory and set that stuff up when I update on pypi and use the webinterface for git. So I finish a bit of code fixes that should be pushed out. I toss it on git, then I update it to pypi, if it's stuff that should also be there. But, then that means updating the PyPI version in the setup file, which I then don't sync consistently back to .git.

**Comment by tatarize** [comment]
And even the version marked as 1.2.9 wasn't. I neglected to trash the old files and move the new files over so I reupdated with the same files. I updated to 1.2.11 and then realized that I messed that up, and quickly made 1.2.12 which actually included updated files.

**Comment by lexelby** [comment]
Thanks!

**Comment by tatarize** [comment]
And the webinterface does have releases which does the tag stuff. So 1.2.12 got tagged so it should work like that going forward.
