### ISSUE TITLE
test suite for pes format

### ISSUE THREAD

**Issue by maxim-s-barabash** [inkstitch/pyembroidery#70]
Hi, I am now implementing support for the pes format for the sk1project/uniconvertor.
If you have a test suite for pes format?
Can you share?
https://github.com/sk1project/sk1-wx/issues/196

**Comment by lexelby** [comment]
Hi!  Sorry I didn't get back to you on this sooner.  Your question is very much welcome here so please don't feel that we were ignoring you on purpose.

I'm sorry to say that we don't have a test suite for the PES format (or any format).  If you create one, we'd love to integrate it into this repo.

sk1 looks pretty neat!  Perhaps someday Ink/Stitch could be made to work with it.

**Comment by maxim-s-barabash** [comment]
Thank you, everything is OK.
We received information from @tatarize

**Comment by lexelby** [comment]
Got it, thanks.  Just as a note to avoid confusion, tatarize is no longer a part of the Ink/Stitch community and this repo is a fork of embroidepy/pyembroidery.
