### ISSUE TITLE
pyembroidery update

### ISSUE THREAD

**Issue by kaalleen** [inkstitch/pyembroidery#71]
In [Ink/Stitch #487](https://github.com/inkstitch/inkstitch/pull/487) we touched an pyembroidery issue which I carried over to the pyembroidery library, because it might help more people if the issue was solved there. @tatarize had a look into it and made some changes to his library to help the recognition of trims and stops on imported files.

The discussion is found [here](https://github.com/EmbroidePy/pyembroidery/issues/62).

He also mentions the encoding issues we were having recently in Ink/Stitch were caused by the pyembroidery library and released a fix for it.

**Comment by lexelby** [comment]
Got it!  I'll take a look and merge in his changes.

**Comment by lexelby** [comment]
Done.  See https://github.com/inkstitch/inkstitch/pull/509 for the results :)
