### ISSUE TITLE
pes stitch seek correct file

### ISSUE THREAD

**Issue by fabricocouto** [inkstitch/pyembroidery#91]
f.seek(0x0F, 1)

to

f.seek(0x0B, 1)

**Comment by kaalleen** [comment]
Thank you so much for your input and explanation. I completely missed this issue. Would you mind to create a pull request to fix it? We are currently short on time and can need any help given. If you wish, we can also add you to this repository as a member.

**Comment by fabricocouto** [comment]
> Thank you so much for your input and explanation. I completely missed this issue. Would you mind to create a pull request to fix it? We are currently short on time and can need any help given. If you wish, we can also add you to this repository as a member.

hello can you add me that I will be honored to participate in the project
